FROM ubuntu:jammy

COPY ./build/blackfuryd /bin/blackfuryd

RUN adduser --system --home /quicksilver --disabled-password --disabled-login quicksilver --uid 1000
USER quicksilver
CMD ["blackfuryd", "start"]
